#:kivy 2.2.0
BoxLayout:
    orientation: "vertical"

    MDTopAppBar:
        title: "Exercises"
        left_action_items: [["arrow-left", lambda x: app.root.current == "HomePage"]]
    
    ScrollView:
        MDList:
            OneLineIconListItem:
                text: "Squats"
                ImageLeftWidget: #256x256 image only!!!!
                    source: "Assets\squat 256x256 image.png"