#:kivy 2.2.0
Screen:
	BoxLayout:
		orientation:'vertical'
	MDBottomNavigation:
		MDBottomNavigationItem:
			name:"Sessions"
			text:"Sessions"
			icon:"Assets\SessionIcon.png"
		
		MDBottomNavigationItem:
			name:"Logs"
			text:"Logs"
			icon:"Assets\LogsIcon.png"

		MDBottomNavigationItem:
			name:"Consult"
			text:"Consult"
			icon:"Assets\ConsultIcon.png"

		MDBottomNavigationItem:
			name:"Profile"
			text:"Profile"
			icon:"Assets\ProfieIcon.png"
